print(1 + 2 + 3)
print(1 + 2 + 3)
print(1 + 2 + 3)
print(1 + 2 + 3)
print(1 + 2 + 3)
print("안녕하세요!")
print("안녕하세요!")

print("hello universe!")
print("hello universe!")
print("hello universe!")
print("hello universe!")
print("hello universe!")
print("hello universe!")
print("hello universe!")
print("hello universe!")
print("hello universe!")

print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")

