print(1 + 2 + 3)
print(1 + 2 + 3)
print(1 + 2 + 3)
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
