print("git충돌연습")
print("hello 하세요!")
print("hello!!!!!!!!!!!!")
print(100)
print("cat")
print('commit2')
print("Tuna")
print("spam")
print("hippo!")

print("안녕하세요!")

print("hello universe!")
print("hello universe!")
print("hi universe!")
print("hello universe!")
print("hi universe!")

print("hello world!")
print("반갑습니다!")
print("hello bear")
print("hello tiger")
print("hello lion!")
print("hi universe!")
print("hi universe!")
print("hi universe!")
print("hi universe!")
print("hi universe!")
